(require 'memoize)
(defun fib (n) (if (<= n 1) n (+ (fib (- n 1)) (fib (- n 2)))))
(memoize fib)
(format t "fib 30 = ~A~%" (fib 30))
(format t "fib 35 = ~A~%" (fib 35))
(let ((tbl (car (cdr (assoc 'fib *memoized-functions*)))))
  (format t "cache size: ~A entries~%" (hash-table-count tbl))
  (format t "test: ~A~%" (hash-table-test tbl)))
(clear-memoized-function 'fib)
(let ((tbl (car (cdr (assoc 'fib *memoized-functions*)))))
  (format t "after clear: ~A entries~%" (hash-table-count tbl)))
(unmemoize-function 'fib)
(format t "after unmemoize: memoized=~A~%" (function-memoized-p 'fib))
;; Verify multi-arg works too
(defun pair-sum (a b) (+ a b))
(memoize pair-sum)
(format t "pair-sum 3 4 = ~A~%" (pair-sum 3 4))
(format t "pair-sum 3 4 again (cached) = ~A~%" (pair-sum 3 4))
(format t "pair-sum 5 6 = ~A~%" (pair-sum 5 6))
