(require 'trace)
(defgeneric greet (x))
(defmethod greet ((x integer)) (* x 2))
(defmethod greet ((x string))  (concatenate 'string "hi " x))
(trace greet)
(format t "= ~A~%" (greet 21))
(format t "= ~A~%" (greet "world"))
(untrace greet)
(format t "after untrace: ~A~%" (greet 5))
