//! Windows API metadata pack loader. Phase 4 of `docs/WINDOWS_FFI.md`.
//!
//! At `--windows` startup the driver loads `packs/windows_api.pack`,
//! a build-time-generated binary file containing one record per
//! Win32 function (DLL, arg types, return type, route, …). Lookups
//! are then O(1) by function name from anywhere in the runtime.
//!
//! The pack is generated by `scripts/generate_win32_pack.py` from
//! `windows_api/windows_api.db` (the WinMD-derived SQLite database
//! shared with the sister NewM2 project). Regenerate when the
//! upstream metadata changes.
//!
//! Pack format
//! ───────────
//! ```text
//!   8 bytes magic = b"NCLPACK1"
//!   u32  format_version  (= 1)
//!   u32  num_functions
//!   { per function:
//!     u16 name_len, name_bytes  (ASCII)
//!     u16 dll_len,  dll_bytes   (ASCII)
//!     u8  ret_tag                (TypeTag)
//!     u8  flags                  (bit 0 = set_last_error; bit 1 = route_ui)
//!     u8  aw_byte                (0, 'A' = 65, 'W' = 87)
//!     u8  num_args
//!     [u8; num_args] arg_tags
//!   }
//! ```
//!
//! All ints little-endian.

use std::collections::HashMap;
use std::path::Path;
use std::sync::OnceLock;

const MAGIC: &[u8; 8] = b"NCLPACK1";
const FORMAT_VERSION: u32 = 1;

/// One function record. `name` and `dll` are leaked into 'static
/// storage so lookups can hand out `&'static str` without
/// per-lookup allocation; the pack lives for the process lifetime.
pub struct WinFn {
    pub name: &'static str,
    pub dll: &'static str,
    pub ret_tag: u8,
    pub arg_tags: &'static [u8],
    pub set_last_error: bool,
    pub route_ui: bool,
    pub aw_family: Option<char>,
}

static PACK: OnceLock<HashMap<&'static str, &'static WinFn>> = OnceLock::new();
static LOAD_ERROR: OnceLock<String> = OnceLock::new();

/// Load the pack from `path`. Idempotent; subsequent calls are
/// silent no-ops (OnceLock semantics). Stores any error in
/// `LOAD_ERROR` so the driver can surface it.
pub fn load_pack(path: &Path) -> Result<(), String> {
    if PACK.get().is_some() {
        return Ok(());
    }
    let bytes = std::fs::read(path)
        .map_err(|e| format!("win_metadata: cannot read {}: {e}", path.display()))?;
    let pack = parse_pack(&bytes)?;
    PACK.set(pack)
        .map_err(|_| "win_metadata: pack already loaded".to_string())?;
    Ok(())
}

/// Try to load the pack, but stash any error rather than
/// returning it. The driver calls this; later calls to `lookup`
/// just see "not in pack" rather than propagating the load
/// failure. Useful when `--windows` is on but the pack file is
/// missing — the surface still partly works (you can call
/// `%ffi-call` directly), and `win32 / defwin32` clearly fail
/// with "function NAME not in metadata pack".
pub fn try_load_pack(path: &Path) {
    if let Err(e) = load_pack(path) {
        let _ = LOAD_ERROR.set(e);
    }
}

pub fn load_error() -> Option<&'static str> {
    LOAD_ERROR.get().map(|s| s.as_str())
}

pub fn is_loaded() -> bool {
    PACK.get().is_some()
}

/// Look up a function by exact name (case-sensitive). Returns
/// None if the pack isn't loaded or the name isn't present.
pub fn lookup(name: &str) -> Option<&'static WinFn> {
    PACK.get()?.get(name).copied()
}

/// Number of functions in the loaded pack, or 0 if not loaded.
pub fn function_count() -> usize {
    PACK.get().map_or(0, |m| m.len())
}

// ─── Parser ───────────────────────────────────────────────────────────

fn parse_pack(bytes: &[u8]) -> Result<HashMap<&'static str, &'static WinFn>, String> {
    let mut cursor = Cursor { buf: bytes, pos: 0 };
    let magic = cursor.read_bytes(8)?;
    if magic != MAGIC {
        return Err(format!(
            "win_metadata: bad magic {:?}, expected {:?}",
            magic, MAGIC
        ));
    }
    let version = cursor.read_u32()?;
    if version != FORMAT_VERSION {
        return Err(format!(
            "win_metadata: pack format version mismatch: file is {version}, runtime expects {FORMAT_VERSION}"
        ));
    }
    let num_funcs = cursor.read_u32()? as usize;
    let mut map = HashMap::with_capacity(num_funcs);
    for _ in 0..num_funcs {
        let name = cursor.read_string_u16()?;
        let dll = cursor.read_string_u16()?;
        let ret_tag = cursor.read_u8()?;
        let flags = cursor.read_u8()?;
        let aw_byte = cursor.read_u8()?;
        let num_args = cursor.read_u8()? as usize;
        let arg_tags_bytes = cursor.read_bytes(num_args)?;

        let aw_family = match aw_byte {
            0 => None,
            b'A' => Some('A'),
            b'W' => Some('W'),
            other => return Err(format!(
                "win_metadata: bad aw_byte {other} for {name:?}")),
        };

        // Leak the slices into 'static storage. The pack lives for
        // the process lifetime; freeing isn't useful.
        let name_static: &'static str = Box::leak(name.into_boxed_str());
        let dll_static: &'static str = Box::leak(dll.into_boxed_str());
        let arg_tags_static: &'static [u8] = Box::leak(arg_tags_bytes.to_vec().into_boxed_slice());

        let wf = Box::leak(Box::new(WinFn {
            name: name_static,
            dll: dll_static,
            ret_tag,
            arg_tags: arg_tags_static,
            set_last_error: (flags & 1) != 0,
            route_ui:        (flags & 2) != 0,
            aw_family,
        }));

        map.insert(name_static, &*wf);
    }
    Ok(map)
}

struct Cursor<'a> {
    buf: &'a [u8],
    pos: usize,
}

impl<'a> Cursor<'a> {
    fn read_bytes(&mut self, n: usize) -> Result<&'a [u8], String> {
        if self.pos + n > self.buf.len() {
            return Err(format!(
                "win_metadata: pack truncated at offset {}", self.pos));
        }
        let r = &self.buf[self.pos..self.pos + n];
        self.pos += n;
        Ok(r)
    }
    fn read_u8(&mut self) -> Result<u8, String> {
        let b = self.read_bytes(1)?;
        Ok(b[0])
    }
    fn read_u16(&mut self) -> Result<u16, String> {
        let b = self.read_bytes(2)?;
        Ok(u16::from_le_bytes([b[0], b[1]]))
    }
    fn read_u32(&mut self) -> Result<u32, String> {
        let b = self.read_bytes(4)?;
        Ok(u32::from_le_bytes([b[0], b[1], b[2], b[3]]))
    }
    fn read_string_u16(&mut self) -> Result<String, String> {
        let len = self.read_u16()? as usize;
        let b = self.read_bytes(len)?;
        // Pack stores ASCII names only; validate on read.
        if !b.is_ascii() {
            return Err("win_metadata: non-ASCII bytes in pack string".into());
        }
        Ok(String::from_utf8(b.to_vec())
            .map_err(|e| format!("win_metadata: utf8 error: {e}"))?)
    }
}
